# -*- coding: utf-8 -*-
"""modules/self/skillforge.py - “kuznitsa navykov”: bezopasnyy chernovik faylov + stat-proverki + vypusk v staging.

Mosty:
- Yavnyy: (Samorazvitie ↔ Bezopasnost) vse novye fayly cherez quarantine i testy.
- Skrytyy #1: (Infoteoriya ↔ Audit) khranenie sha i otchetov testa v papke karantina.
- Skrytyy #2: (Kibernetika ↔ Distsiplina) vypusk tolko v razreshennye katalogi i cherez stage→approve.

Zemnoy abzats:
Kak masterskaya: chertili - proverili - vynesli v predbannik - dalshe uzhe ofitsialnyy put.

# c=a+b"""
from __future__ import annotations
import base64, json, os, re
from typing import Any, Dict
from modules.memory.facade import memory_add, ESTER_MEM_FACADE

FORGE_AB = (os.getenv("FORGE_AB","A") or "A").upper()
ALLOW = [d.strip() for d in (os.getenv("FORGE_ALLOW_DIRS","modules,routes,templates,static,data").split(",")) if d.strip()]

def _allowed_path(path: str) -> bool:
    norm = os.path.normpath(path).replace("\\","/")
    return any(norm.startswith(d+"/") or norm==d for d in ALLOW)

def draft(path: str, rfc: str, kind: str, content_b64: str | None = None) -> Dict[str, Any]:
    """Creates a draft in quarantine. If content_b64 is missing, we generate a template."""
    if not _allowed_path(path):
        return {"ok": False, "error":"path_not_allowed"}
    if content_b64 is None:
        tpl = _make_template(path, kind, rfc)
        content_b64 = base64.b64encode(tpl.encode("utf-8")).decode("ascii")
    try:
        from modules.quarantine.storage import ingest  # type: ignore
    except Exception:
        return {"ok": False, "error":"quarantine_unavailable"}
    meta={"rfc": rfc, "kind": kind, "path": path}
    rep = ingest(path, content_b64, meta)
    return rep

def _make_template(path: str, kind: str, rfc: str) -> str:
    if path.endswith(".py"):
        if kind == "route":
            bp_name = os.path.basename(path).replace(".py", "")
            return (
                "# -*- coding: utf-8 -*-\n"
                f"\"\"\"\n{path} - new route module (generated by skillforge).\n\"\"\"\n"
                "from __future__ import annotations\n"
                "from flask import Blueprint, jsonify\n"
                f"bp = Blueprint({json.dumps(bp_name)}, __name__)\n\n"
                "def register(app):\n"
                "    app.register_blueprint(bp)\n"
                "    return app\n\n"
                "@bp.route('/demo/ok', methods=['GET'])\n"
                "def ok():\n"
                f"    return jsonify({{'ok': True, 'rfc': {json.dumps(rfc)}}})\n"
            )
        return (
            "# -*- coding: utf-8 -*-\n"
            f"\"\"\"\n{path} - module template (generated by skillforge).\n\"\"\"\n"
            "from __future__ import annotations\n\n"
            "def main():\n"
            "    return {'ok': True}\n"
        )
    if path.endswith(".html"):
        return f"<!doctype html><meta charset='utf-8'><title>{path}</title>"
    if path.endswith(".json"):
        return json.dumps({"rfc": rfc, "note":"template"}, ensure_ascii=False, indent=2)
    return f"// {path} - template\n"

def test(qid: str) -> Dict[str, Any]:
    """Become-check: decode, for .po - ast.parse, prohibition of dangerous tokens; for route - the presence of register()."""
    try:
        from modules.quarantine.storage import QUAR_DIR  # type: ignore
    except Exception:
        return {"ok": False, "error":"quarantine_unavailable"}
    base = os.path.join(QUAR_DIR, qid)
    src = os.path.join(base,"src.bin")
    if not os.path.isfile(src): return {"ok": False, "error":"not_found"}
    raw = open(src,"rb").read().decode("utf-8","ignore")
    res={"lang":"txt","checks":[],"ok": True}
    import ast
    if path := (json.load(open(os.path.join(base,"meta.json"),"r",encoding="utf-8")).get("path") or ""):
        if path.endswith(".py"):
            res["lang"]="py"
            # zaprety
            bad=re.compile(r"\b(os\.system|subprocess\.|eval\(|exec\(|open\(/etc|\bimport\s+socket\b)", re.I)
            if bad.search(raw): res["checks"].append({"deny":"dangerous_token"}); res["ok"]=False
            # AST
            try:
                ast.parse(raw)
                res["checks"].append({"ast":"ok"})
            except Exception as e:
                res["checks"].append({"ast":f"error:{e}"}); res["ok"]=False
            # route: register(app)
            if "Blueprint(" in raw and "def register(app):" not in raw:
                res["checks"].append({"register":"missing"}); res["ok"]=False
    open(os.path.join(base,"test.json"),"w",encoding="utf-8").write(json.dumps(res,ensure_ascii=False,indent=2))
    return {"ok": True, "result": res}

def apply(qid: str, reason: str = "") -> Dict[str, Any]:
    """
    Vypusk v staging (cherez quarantine.storage.release_to_staging). FORGE_AB=B — zapret.
    """
    if FORGE_AB=="B": return {"ok": False, "error":"FORGE_AB=B"}
    try:
        from modules.quarantine.storage import rescan, release_to_staging  # type: ignore
    except Exception:
        return {"ok": False, "error":"quarantine_unavailable"}
    rep = rescan(qid)
    if not rep.get("ok",False): return rep
    # If the test is not passed, we will not release
    try:
        from modules.quarantine.storage import QUAR_DIR  # type: ignore
        t = json.load(open(os.path.join(os.path.join(QUAR_DIR,qid),"test.json"),"r",encoding="utf-8"))
        if not t.get("result",{}).get("ok",False):
            return {"ok": False, "error":"test_failed", "detail": t}
    except Exception:
        return {"ok": False, "error":"no_test_result"}
    # kuda vypuskat
    meta = json.load(open(os.path.join(os.path.join(QUAR_DIR,qid),"meta.json"),"r",encoding="utf-8"))
    path = meta.get("path","")
    if not _allowed_path(path): return {"ok": False, "error":"path_not_allowed"}
    return release_to_staging(qid, path, reason or "skillforge_apply")
# c=a+b
