apiVersion: 1

datasources:
  - name: k6-influx
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    database: k6
    basicAuth: false
    isDefault: true
    editable: true
