{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "ester.fullname" . }}
  labels:
    {{- include "ester.labels" . | nindent 4 }}
spec:
  host: {{ include "ester.fullname" . }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "ester.fullname" . }}-canary
  labels:
    {{- include "ester.labels" . | nindent 4 }}
spec:
  host: {{ include "ester.fullname" . }}-canary
{{- end }}
