apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ester.fullname" . }}-env
  labels:
    {{- include "ester.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.env.JWT_SECRET | quote }}
  ENCRYPTION_MASTER_KEY_BASE64: {{ .Values.env.ENCRYPTION_MASTER_KEY_BASE64 | quote }}
