{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ester.fullname" . }}
  labels:
    {{- include "ester.labels" . | nindent 4 }}
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ester.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "5s" }}
      scheme: {{ .Values.serviceMonitor.scheme | default "http" }}
{{- end }}
