"""SYNAPS protocol sidecar contracts."""

from .protocol import (
    SCHEMA_VERSION,
    SynapsAuthStatus,
    SynapsConfig,
    SynapsEnvelope,
    SynapsHealth,
    SynapsHealthState,
    SynapsInboundResult,
    SynapsMessageType,
    SynapsPreparedRequest,
    SynapsValidationError,
    build_envelope,
    config_from_env,
    hash_content,
    parse_inbound_payload,
    prepare_outbound_request,
    synaps_health,
    to_record,
    verify_token,
)
from .adapter import (
    SynapsRouteResponse,
    handle_inbound_payload,
    handle_inbound_payload_async,
    prepare_chat_message,
    prepare_thought_request,
)
from .listener_bridge import (
    DEFAULT_SISTER_SYSTEM_PROMPT,
    build_safe_chat_thought_handler,
    config_from_legacy_listener_values,
    log_synaps_route_response,
    make_sister_inbound_view,
    read_payload_safely,
    run_awaitable_in_new_loop,
)

__all__ = [
    "DEFAULT_SISTER_SYSTEM_PROMPT",
    "SCHEMA_VERSION",
    "SynapsAuthStatus",
    "SynapsConfig",
    "SynapsEnvelope",
    "SynapsHealth",
    "SynapsHealthState",
    "SynapsInboundResult",
    "SynapsMessageType",
    "SynapsPreparedRequest",
    "SynapsRouteResponse",
    "SynapsValidationError",
    "build_envelope",
    "build_safe_chat_thought_handler",
    "config_from_env",
    "config_from_legacy_listener_values",
    "hash_content",
    "handle_inbound_payload",
    "handle_inbound_payload_async",
    "log_synaps_route_response",
    "make_sister_inbound_view",
    "parse_inbound_payload",
    "prepare_chat_message",
    "prepare_outbound_request",
    "prepare_thought_request",
    "read_payload_safely",
    "run_awaitable_in_new_loop",
    "synaps_health",
    "to_record",
    "verify_token",
]
